name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip fire homeassistant
        python3 requirements_from_manifest.py custom_components/blnet/manifest.json > requirements.txt
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s custom_components/blnet/tests